### ISSUE TITLE
Make the cmath library working on the kernel

### ISSUE THREAD

**Issue by 1e-to** [IntelPython/numba-dppy#172]
Now functions from the сmatch do not work on the kernel

**Comment by chudur-budur** [comment]
`cmath` is not still recognized inside the kernel (experimental).

```python
import numba_dpex as ndpx
import numba_dpex.experimental as ndpxp
from numba_dpex import Range
import cmath
import math
import dpnp

mlib = None


@ndpxp.kernel
def foo(a):
    i = ndpx.get_global_id(0)
    a[i] = math.cos(a[i])


@ndpxp.kernel
def bar(a):
    i = ndpx.get_global_id(0)
    a[i] = cmath.cos(a[i])


u = dpnp.linspace(0, 1.0, 10)
print(u)

print("========== math.cos ==========")
ndpxp.call_kernel(foo, Range(u.shape[0]), u)
print(u)

print("========== cmath.cos ==========")
ndpxp.call_kernel(bar, Range(u.shape[0]), u)
print(u)
```

output:
```bash
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
========== math.cos ==========
[1.         0.99383351 0.97541009 0.94495695 0.90284967 0.84960756
 0.78588726 0.71247462 0.63027505 0.54030231]
========== cmath.cos ==========
Traceback (most recent call last):
  File "/localdisk/work/$USER/numba-dpex/my-driver.py", line 673, in <module>
    ndpxp.call_kernel(bar, Range(u.shape[0]), u)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in dpex_dpjit_nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<intrinsic _submit_kernel_sync>) found for signature:

 >>> _submit_kernel_sync(type(KernelDispatcher(<function bar at 0x7fdcbd80f520>)), Range<1>, UniTuple(DpnpNdArray(dtype=float64, ndim=1, layout=C, address_space=1, usm_type=device, device=level_zero:gpu:0, sycl_queue=DpctlSyclQueue on level_zero:gpu:0) x 1))

There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Intrinsic in function '_submit_kernel_sync': File: ../../../../../../../numba-dpex/numba_dpex/experimental/launcher.py: Line 72.
    With argument(s): '(type(KernelDispatcher(<function bar at 0x7fdcbd80f520>)), Range<1>, UniTuple(DpnpNdArray(dtype=float64, ndim=1, layout=C, address_space=1, usm_type=device, device=level_zero:gpu:0, sycl_queue=DpctlSyclQueue on level_zero:gpu:0) x 1))':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in dpex_kernel_nopython mode pipeline (step: nopython frontend)
   No implementation of function Function(<built-in function setitem>) found for signature:

    >>> setitem(DpnpNdArray(dtype=float64, ndim=1, layout=C, address_space=1, usm_type=device, device=level_zero:gpu:0, sycl_queue=DpctlSyclQueue on level_zero:gpu:0), int64, complex128)

   There are 16 candidate implementations:
     - Of which 16 did not match due to:
     Overload of function 'setitem': File: <numerous>: Line N/A.
       With argument(s): '(DpnpNdArray(dtype=float64, ndim=1, layout=C, address_space=1, usm_type=device, device=level_zero:gpu:0, sycl_queue=DpctlSyclQueue on level_zero:gpu:0), int64, complex128)':
      No match.

   During: typing of setitem at /localdisk/work/$USER/numba-dpex/my-driver.py (662)

   File "my-driver.py", line 662:
   def bar(a):
       <source elided>
       i = ndpx.get_global_id(0)
       a[i] = cmath.cos(a[i])
       ^

  raised from /localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/typeinfer.py:1086

During: resolving callee type: Function(<intrinsic _submit_kernel_sync>)
During: typing of call at /localdisk/work/$USER/numba-dpex/numba_dpex/experimental/launcher.py (213)


File "numba_dpex/experimental/launcher.py", line 213:
def call_kernel(kernel_fn, index_space, *kernel_args) -> None:
    <source elided>
    """
    _submit_kernel_sync(  # pylint: disable=E1120
    ^

```

**Comment by chudur-budur** [comment]
`cmath` still doesn't work inside kernel (experimental).

```python
import numpy as np
from numba import njit
import numba_dpex as ndpx
import numba_dpex.experimental as ndpxp
from numba_dpex import Range
import cmath
import dpnp


@njit
def foo(a):
    a[0] = cmath.cos(a[0])


@ndpxp.kernel
def bar(a):
    a[0] = cmath.cos(a[0])


t = np.array([1 + 1j])
foo(t)
print(t)

t = np.array([1 + 1j])
u = dpnp.asarray(t)
print(u)

ndpxp.call_kernel(bar, Range(u.shape[0]), u)
print(u)
```

This is the output:

```bash
[0.83373003-0.98889771j]
[1.+1.j]
Traceback (most recent call last):
  File "/localdisk/work/$USER/numba-dpex/my-driver.py", line 669, in <module>
    ndpxp.call_kernel(bar, Range(u.shape[0]), u)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/dispatcher.py", line 487, in _compile_for_args
    raise e
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/localdisk/work/$USER/numba-dpex/numba_dpex/core/dpjit_dispatcher.py", line 35, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/compiler.py", line 770, in compile_extra
    return pipeline.compile_extra(func)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/compiler.py", line 461, in compile_extra
    return self._compile_bytecode()
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/compiler.py", line 529, in _compile_bytecode
    return self._compile_core()
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/compiler.py", line 504, in _compile_core
    raise e
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/compiler.py", line 495, in _compile_core
    pm.run(self.state)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 364, in run
    raise e
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/typed_passes.py", line 110, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/typed_passes.py", line 91, in type_inference_stage
    errs = infer.propagate(raise_errors=raise_errors)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/typeinfer.py", line 1078, in propagate
    errors = self.constraints.propagate(self)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/typeinfer.py", line 177, in propagate
    raise e
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/typeinfer.py", line 155, in propagate
    constraint(typeinfer)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/typeinfer.py", line 578, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/typeinfer.py", line 601, in resolve
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/typeinfer.py", line 1557, in resolve_call
    return self.context.resolve_function_type(fnty, pos_args, kw_args)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/typing/context.py", line 196, in resolve_function_type
    res = self._resolve_user_function_type(func, args, kws)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/typing/context.py", line 248, in _resolve_user_function_type
    return func.get_call_type(self, args, kws)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/types/functions.py", line 312, in get_call_type
    raise e
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/types/functions.py", line 308, in get_call_type
    sig = temp.apply(nolitargs, nolitkws)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/typing/templates.py", line 351, in apply
    sig = generic(args, kws)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/typing/templates.py", line 965, in generic
    result = self._definition_func(self.context, *args, **kws)
  File "/localdisk/work/$USER/numba-dpex/numba_dpex/experimental/launcher.py", line 80, in _submit_kernel_sync
    return _submit_kernel(
  File "/localdisk/work/$USER/numba-dpex/numba_dpex/experimental/launcher.py", line 137, in _submit_kernel
    kcres: _KernelCompileResult = kernel_dispatcher.get_compile_result(
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/dispatcher.py", line 986, in get_compile_result
    self.compile(atypes)
  File "/localdisk/work/$USER/numba-dpex/numba_dpex/experimental/kernel_dispatcher.py", line 430, in compile
    kcres: _KernelCompileResult = compiler.compile(
  File "/localdisk/work/$USER/numba-dpex/numba_dpex/experimental/kernel_dispatcher.py", line 192, in compile
    status, kcres = self._compile_cached(args, return_type)
  File "/localdisk/work/$USER/numba-dpex/numba_dpex/experimental/kernel_dispatcher.py", line 239, in _compile_cached
    cres: CompileResult = self._compile_core(args, return_type)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/compiler.py", line 770, in compile_extra
    return pipeline.compile_extra(func)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/compiler.py", line 461, in compile_extra
    return self._compile_bytecode()
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/compiler.py", line 529, in _compile_bytecode
    return self._compile_core()
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/compiler.py", line 504, in _compile_core
    raise e
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/compiler.py", line 495, in _compile_core
    pm.run(self.state)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 364, in run
    raise e
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/localdisk/work/$USER/numba-dpex/numba_dpex/core/passes/passes.py", line 197, in run_pass
    ret = NativeLowering.run_pass(self, state)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/typed_passes.py", line 466, in run_pass
    lower.lower()
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/lowering.py", line 187, in lower
    self.lower_normal_function(self.fndesc)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/lowering.py", line 241, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/lowering.py", line 271, in lower_function_body
    self.lower_block(block)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/lowering.py", line 285, in lower_block
    self.lower_inst(inst)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/lowering.py", line 463, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/lowering.py", line 675, in lower_assign
    return self.lower_expr(ty, value)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/lowering.py", line 1211, in lower_expr
    res = self.lower_call(resty, expr)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/lowering.py", line 940, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/lowering.py", line 1174, in _lower_call_normal
    impl = self.context.get_function(fnty, signature)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/base.py", line 556, in get_function
    return self.get_function(fn, sig, _firstcall=False)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/base.py", line 558, in get_function
    raise NotImplementedError("No definition for lowering %s%s" % (key, sig))
NotImplementedError: No definition for lowering <built-in function cos>(complex128,) -> complex128
```
