### ISSUE TITLE
Test fails with CPU activated: test_with_dppl_context_cpu

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dppy#18]
Test: test_with_dppl_context_cpu
```
FAIL: test_with_dppl_context_cpu (numba.dppl.tests.dppl.test_with_context.TestWithDPPLContext)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/localdisk/work/spokhode/numba/numba/dppl/tests/dppl/test_with_context.py", line 61, in test_with_dppl_context_cpu
    np.testing.assert_array_equal(expected, got_cpu)
  File "/localdisk/work/spokhode/miniconda3/envs/numba-dppy-dev/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 936, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/localdisk/work/spokhode/miniconda3/envs/numba-dppy-dev/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 770, in assert_array_compare
    flagged = func_assert_same_pos(x, y, func=isnan, hasval='nan')
  File "/localdisk/work/spokhode/miniconda3/envs/numba-dppy-dev/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 746, in func_assert_same_pos
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

x and y nan location mismatch:
 x: array([0.841471, 0.841471, 0.841471, 0.841471, 0.841471, 0.841471,
       0.841471, 0.841471, 0.841471, 0.841471, 0.841471, 0.841471,
       0.841471, 0.841471, 0.841471, 0.841471, 0.841471, 0.841471,...
 y: array([6.790387e-313, 5.360589e-290, 4.653499e-310, 2.376456e-321,
       4.653448e-310, 4.653448e-310, 8.487983e-314, 4.653537e-310,
       4.653447e-310, 2.139304e-321, 4.653448e-310, 6.902090e-310,...
```

Scenario:
1. Checkout tag: 0.51.2+dppy0.11.0 (https://github.com/IntelPython/numba/commit/fc190bf339c83fa461b33e9f14cb35ad756dcb4c)
2. Build in development mode: `python setup.py develop`
3. Activate oneAPI compiler and tbb for enable CPU devices:
```bash
source /opt/intel/oneapi/compiler/latest/env/vars.sh
source /opt/intel/oneapi/tbb/latest/env/vars.sh
```
4. Run tests: `./runtests.py numba.dppl.tests -v -k test_with_dppl_context_cpu`

**Comment by PokhodenkoSA** [comment]
@AlexanderKalistratov @1e-to 
Do you have any ideas about it?

**Comment by PokhodenkoSA** [comment]
Set as `expectedFailure` in #19.
Also related test for GPU fails only on Windows: `test_with_dppl_context_gpu`.

**Comment by PokhodenkoSA** [comment]
Possible fixed. Need check.

**Comment by PokhodenkoSA** [comment]
Not reproduced.
