### ISSUE TITLE
Using USMShared from dpctl.memory is throwing Kernel submission error

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba-dppy#256]
Error:
```
Native API failed. Native API returns: -50 (CL_INVALID_ARG_VALUE) -50 (CL_INVALID_ARG_VALUE)
Traceback (most recent call last):
  File "dpctl_test.py", line 28, in <module>
    VectorAdd[1024,](a, b, c)
  File "/home/adarshyoga/.conda/envs/python-gold/lib/python3.7/site-packages/numba_dppy/compiler.py", line 523, in __call__
    cfg(*args)
  File "/home/adarshyoga/.conda/envs/python-gold/lib/python3.7/site-packages/numba_dppy/compiler.py", line 384, in __call__
    self.sycl_queue.submit(self.kernel, kernelargs, self.global_size, self.local_size)
  File "dpctl/_sycl_core.pyx", line 455, in dpctl._sycl_core.SyclQueue.submit
  File "dpctl/_sycl_core.pyx", line 550, in dpctl._sycl_core.SyclQueue.submit
  File "dpctl/_sycl_core.pyx", line 337, in dpctl._sycl_core.SyclQueue._raise_queue_submit_error
dpctl._sycl_core.SyclKernelSubmitError: Kernel submission to Sycl queue failed.
(python-gold) adarshyoga@iris04:~/work/play> emacs dpctl_test.py
(python-gold) adarshyoga@iris04:~/work/play> python dpctl_test.py
Native API failed. Native API returns: -50 (CL_INVALID_ARG_VALUE) -50 (CL_INVALID_ARG_VALUE)
Traceback (most recent call last):
  File "dpctl_test.py", line 28, in <module>
    VectorAdd[1024,32](a, b, c)
  File "/home/adarshyoga/.conda/envs/python-gold/lib/python3.7/site-packages/numba_dppy/compiler.py", line 523, in __call__
    cfg(*args)
  File "/home/adarshyoga/.conda/envs/python-gold/lib/python3.7/site-packages/numba_dppy/compiler.py", line 384, in __call__

```

Test reproducer:
```
import sys
import numpy as np
import numba_dppy
import dpctl
import dpctl.memory as dpctl_mem
 
@numba_dppy.kernel
def VectorAdd(a, b, c):
      i = numba_dppy.get_global_id(0)
     c[i] = a[i] + b[i]

abuf = dpctl_mem.MemoryUSMShared(1024*np.dtype('i').itemsize)
bbuf = dpctl_mem.MemoryUSMShared(1024*np.dtype('i').itemsize)
cbuf = dpctl_mem.MemoryUSMShared(1024*np.dtype('i').itemsize)
a = np.ndarray((1024), buffer=abuf, dtype='i')
b = np.ndarray((1024), buffer=bbuf, dtype='i')
c = np.ndarray((1024), buffer=cbuf, dtype='i')

for i in range(1024):
      a[i] = i
      b[i] = 2*i

if dpctl.has_gpu_queues():
      with dpctl.device_context("opencl:gpu"):
            VectorAdd[1024,32](a, b, c)
else:
      print("No GPU device found")
      exit()

print(c)
```

**Comment by reazulhoque** [comment]
@adarshyoga  The issue here is we are using different  SYCL queue for allocating data and when submitting the kernel. Moving
```
if dpctl.has_gpu_queues():
      with dpctl.device_context("opencl:gpu"):
```
above `abuf` will stop this error from occouring. Can you please check and confirm?

**Comment by adarshyoga** [comment]
Reazul's suggestion solves the problem.
