### ISSUE TITLE
Example usm_ndarray.py fails

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dppy#436]
```python-traceback
$ python numba_dppy/examples/usm_ndarray.py
N 10
Scheduling on ...
    Name            Intel(R) UHD Graphics [0x9bca]
    Driver version  1.1.19883
    Vendor          Intel(R) Corporation
    Profile         FULL_PROFILE
    Filter string   level_zero:gpu:0
A :  <dpctl.tensor._usmarray.usm_ndarray object at 0x7f7eac05f400>
B :  <dpctl.tensor._usmarray.usm_ndarray object at 0x7f7eac05f3a0>
Traceback (most recent call last):
  File "numba_dppy/examples/usm_ndarray.py", line 72, in <module>
    main()
  File "numba_dppy/examples/usm_ndarray.py", line 64, in main
    driver(da, db, dc, global_size)
  File "numba_dppy/examples/usm_ndarray.py", line 36, in driver
    data_parallel_sum[global_size, dppy.DEFAULT_LOCAL_SIZE](a, b, c)
  File "/localdisk/work/spokhode/numba-dppy/numba_dppy/compiler.py", line 593, in __call__
    cfg(*args)
  File "/localdisk/work/spokhode/numba-dppy/numba_dppy/compiler.py", line 411, in __call__
    self._unpack_argument(
  File "/localdisk/work/spokhode/numba-dppy/numba_dppy/compiler.py", line 495, in _unpack_argument
    raise NotImplementedError(ty, USMNdArrayType)
NotImplementedError: (USM:ndarray(float32, 1d, C), <class 'numba_dppy.driver.usm_ndarray_type.USMNdArrayType'>)
```

**Comment by PokhodenkoSA** [comment]
@diptorupd
Do you have an idea?

**Comment by reazulhoque** [comment]
@PokhodenkoSA This is the expected behavior. We have added the hooks to be able to handle usm_ndarray. The implementation is still missing. This example points out that we currently do not support usm_ndarray from the user perspective but is a feature that is coming.
